######################## default configuration ####################
baseURL = "https://businessai.raulferrer.dev/"
title = "Artificial Intelligence in Business Management"
theme = "apollo-hugo"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "20"
# google analytics
googleAnalytics = "G-3QQB7Q8T9Y" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
# [[params.plugins.css]]
# link = ""

# JS Plugins
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"

###################### Navigation ###########################

# main menu

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "about/"
weight = 2
  
#[[menu.main]]
#name = "Elemetns"
#url = "elements/"
#weight = 2
  
[[menu.main]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3
  
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 4

#################### default parameters ############################
[params]
logo = "images/logo.png"
logo_width = "150x"
favicon = "images/favicon.png"
# Meta data
description = "Smart Business AI delves into the world of Artificial Intelligence, exploring how it can help streamline operations, enhance decision-making, and build long-lasting customer relationships."
author = "Raúl Ferrer"
# main section
main_section = "post"
# banner content
banner_content = "If you're looking to stay ahead of the competition in today's fast-paced business world, **AI Business Management** is the way to go. **Smart Business AI** delves into the world of AI, exploring how it can help streamline operations, enhance decision-making, and build long-lasting customer relationships. Discover how businesses of all sizes can leverage intelligent algorithms and machine learning to automate routine tasks, generate actionable insights, and make data-driven decisions. Don't miss out on this opportunity to learn about the future of business management – read our latest blog today!"
# copyright
copyright = "@ Smart Business AI - 2023"
# custom script on header
custom_script= ""

# site variables
[params.variables]
primary_color = "#D14124"
body_color = "#fff"
text_color = "#333"
text_color_dark = "#000"
text_color_light = "#999"
border_color = "#e2e2e2"
black = "#000"
white = "#fff"
light = "#f1f1f1"

# font variable
# Give your font name from google font. and add font weight using comma, ex: "Roboto:400,500,900"
primary_font = "Raleway:100,200,300,400,500,600,700,800,900"
icon_font = "Fontawesome 5 Free"

# cookies
[params.cookies]
enable = false
expire_days = 2

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"